# Site settings
title: Vikram Vishal Singh
subtitle: Projects
email: vvsbnmit@gmail.com
description: "My journey of AI"
baseurl: ""
url: "https://vvsbnmit.github.io"
twitter: vikramvishal90
email: vikram.singh@uconn.edu
github:  vvsbnmit
linkedin: "vvs"

google_tracking_id : UA-157821185-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 50
exclude: ["less","node_modules","Gruntfile.js","package.json"]

theme: jekyll-theme-cayman

gems: [jekyll-paginate, jekyll-feed]
