# Site settings
title: Vikram Vishal Singh
subtitle: Projects
email: vvsbnmit@gmail.com
description: "My journey of AI"
baseurl: ""
url: "https://vvsbnmit.github.io"
twitter: vikramvishal90
github:  vvsbnmit
linkedin: "vvs"

google_tracking_id : UA-157821185-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

theme: jekyll-theme-cayman

gems: [jekyll-paginate, jekyll-feed]
