# Site settings
title: Vikram Vishal Singh
subtitle: Projects
email: vvsbnmit@gmail.com
description: "My journey of AI"
baseurl: ""
url: "https://vvsbnmit.github.io"
twitter_username: vikramvishal90
github_username:  vvsbnmit

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

analytics :
  provider : google
  google:
    tracking_id : 'UA-157821185-1'
  getclicky :
    site_id

theme: jekyll-theme-cayman